### ISSUE TITLE
wowpm details

### ISSUE THREAD

**Issue by torkus** [karolswdev/wow#1]
Hi @karolswdev , I maintain a list of addon managers for WoW here: 
https://github.com/ogri-la/wowman#other-addon-managers

* is karolswdev/wow windows-only ?
* any plans on supporting retail?
* could you attach a licence to your repository? this helps me distinguish between 'source available' and 'free/open source' software and would definitely help anyone looking to ~contributute~ contribute.

**Comment by karolswdev** [comment]
Hi @torkus, thank you very much for showing interest in wowpm.

* karolswdev/wow is Linux, Mac and Windows
* no plans on supporting retail at all for now
* will look into the license, it's early days, but most likely MIT

**Comment by torkus** [comment]
thanks, @karolswdev :)

> karolswdev/wow is Linux, Mac and Windows

isn't MSSQL windows-only?

**Comment by torkus** [comment]
I've just taken a peek at the rest of the code and think I've pounced too early ;) good luck with wowpm, I look forward to seeing how it grows

**Comment by karolswdev** [comment]
Yes, it's VERY early days @torkus, I'll have more commits going in soon. MSSQL has now a Linux binary too, but anyway, that part is for the back-end. The only thing that clients will be concerned with will most likely be the CLI client as well as the website that'll be built for it :)
